name: 2e Leatherworks
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffa'
    - '#1e110b'
    - '#6c6932'
    - '#667dcb'
    - '#cbbbbc'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
